const cities = [
  { id: 1, name: 'tunis' },
  { id: 2, name: 'ariana' },
  { id: 3, name: 'ben arous' },
  { id: 4, name: 'manouba' },
  { id: 5, name: 'nabeul' },
  { id: 6, name: 'zaghouan' },
  { id: 7, name: 'bizerte' },
  { id: 8, name: 'béja' },
  { id: 9, name: 'jendouba' },
  { id: 10, name: 'kef' },
  { id: 11, name: 'siliana' },
  { id: 12, name: 'sousse' },
  { id: 13, name: 'monastir' },
  { id: 14, name: 'mahdia' },
  { id: 15, name: 'sfax' },
  { id: 16, name: 'kairouan' },
  { id: 17, name: 'kasserine' },
  { id: 18, name: 'sidi bouzid' },
  { id: 19, name: 'gabès' },
  { id: 20, name: 'medenine' },
  { id: 21, name: 'tataouine' },
  { id: 22, name: 'tozeur' },
  { id: 23, name: 'kebili' },
  { id: 24, name: 'gafsa' },
];

export { cities };
