const cities = [
  { id: 1, name: 'Tunis' },
  { id: 2, name: 'Ariana' },
  { id: 3, name: 'Ben Arous' },
  { id: 4, name: 'Manouba' },
  { id: 5, name: 'Nabeul' },
  { id: 6, name: 'Zaghouan' },
  { id: 7, name: 'Bizerte' },
  { id: 8, name: 'Béja' },
  { id: 9, name: 'Jendouba' },
  { id: 10, name: 'Kef' },
  { id: 11, name: 'Siliana' },
  { id: 12, name: 'Sousse' },
  { id: 13, name: 'Monastir' },
  { id: 14, name: 'Mahdia' },
  { id: 15, name: 'Sfax' },
  { id: 16, name: 'Kairouan' },
  { id: 17, name: 'Kasserine' },
  { id: 18, name: 'Sidi Bouzid' },
  { id: 19, name: 'Gabès' },
  { id: 20, name: 'Medenine' },
  { id: 21, name: 'Tataouine' },
  { id: 22, name: 'Tozeur' },
  { id: 23, name: 'Kebili' },
  { id: 24, name: 'Gafsa' },
];

export { cities };
